config/routes.rb
Rails.application.routes.draw do
  # get 'cocktails/index'
  # get 'cocktails/show'
  # get 'cocktails/new'
  # get 'cocktails/create'
  # resources :cocktails, only: [:index, :show, :new, :create]
  root to: "cocktails#home"
  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:edit, :update, :destroy]
  resources :reviews, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# nested resources is the same as using member

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy

  validates :photo, presence: true
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def home
  end

  def index
    if params[:search]
      @cocktails = Cocktail.where("name iLIKE '%#{params[:search]}%'")
    else
      @cocktails = Cocktail.all
    end
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :ingredients, :doses, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_dose, only: [:edit, :update, :destroy]

  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @dose.update(dose_params)
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :edit
    end
  end

  def destroy
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
    # los permit() lo del parentesis es lo que cogo de la form
    # no pongo :cocktails_id pq eso lo saco de params del link
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="photo-uploader">
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions btn btn-outline-success">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Edit Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Cancel', cocktails_path %>

app/views/cocktails/home.html.erb
<div class="red-background">
  <%= link_to cocktails_path do %>
    <%= image_tag "final-logo.png", size: "500x500"%>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="title text-center p-3">
  <h1>Cocktails</h1>
</div>

<div class="cards container">

  <% @cocktails.each do |cocktail| %>
    <%= link_to cocktail_path(cocktail) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>')">
        <%= cocktail.name %>
      </div>
    <% end %>
  <% end %>
</div>


        <%#= link_to edit_cocktail_path(cocktail) do %>
          <!-- <i class="far fa-edit"></i> -->
        <%# end %>
<%#= link_to "<i class='far fa-edit'></i>".html_safe, edit_cocktail_path(cocktail) %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Cancel', cocktails_path %>

app/views/cocktails/show.html.erb
<br>
<div class="container d-sm-flex justify-content-between pic-ing-rev">

  <div class="card-cocktail" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo, height: 800, width: 400, crop: :fill %>')">
    <%= @cocktail.name %>
    <div class="edit">
      <%= link_to edit_cocktail_path(@cocktail) do %>
          <i class="far fa-edit"></i>
      <% end %>
      <%= link_to cocktail_path(@cocktail), method: :delete,data: { confirm: "Are you sure you want to delete this cocktail?" } do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    </div>
  </div>

    <div class="ingredients">
      <h3>Ingredients</h3>
      <ul>
          <% @cocktail.doses.each do |dose| %>
          <li>
          <p>
            <%= dose.description %> - <%= dose.ingredient.name %> |
            <%= link_to edit_dose_path(dose) do %>
              <i class="far fa-edit"></i>
            <% end %>
            <%= link_to dose_path(dose), method: :delete,data: { confirm: "Are you sure?" } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </p>
          </li>
          <% end %>
      </ul>
      <br>
      <br>
      <div class="dose-form container">
        <h4>New ingredient</h4>
          <%= render "doses/form", cocktail: @cocktail, dose: Dose.new %>
        <br>
      </div>
    </div>

    <div class="reviews">
      <h3>Reviews</h3>
      <ul>
          <% @cocktail.reviews.each do |review| %>
            <li>
              <% review.rating.times do |time| %>
                <i class="fas fa-star"></i>
              <% end %>
              <% (5 - review.rating).times do |time| %>
                <i class="far fa-star"></i>
              <% end %> -
              <%= review.content %>
              <!-- | -->
              <%#= link_to edit_review_path(review) do %>
                  <!-- <i class="far fa-edit"></i> -->
              <%# end %>
              <%#= link_to review_path(review), method: :delete,data: { confirm: "Are you sure?" } do %>
                <!-- <i class="far fa-trash-alt"></i> -->
              <%# end %>
          <% end %>
            <li>
      </ul>
    </p>
    <br>
    <br>
    <div class="review-form container">
      <h4>New review</h4>
      <%= render "reviews/form", cocktail: @cocktail, review: Review.new %>
    </div>
    </div>
</div>




<div class="container">
  <%= link_to 'Back', cocktails_path, class: "btn btn-outline-primary" %>
</div>

<%#= link_to 'Add new dose', new_cocktail_dose_path(@cocktail) %>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
<%= f.association :ingredient %>
<%= f.input :description %>
<%= f.submit class: "btn btn-outline-success btn-block"%>
<% end %>

app/views/doses/edit.html.erb
<h1>Edit dose</h1>

<%= render 'form', dose: @dose %>

<%= link_to 'Cancel', cocktail_path(@dose.cocktail) %>

app/views/doses/new.html.erb
<h1>New dose</h1>

<%= render 'form', dose: @dose %>

<%= link_to 'Cancel', cocktail_path(@cocktail) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# unless params[:controller] == "cocktails" && params[:action] == "home" %>
      <%= render "shared/navbar" %>
      <%# end %>
    <div class="content">
      <%= yield %>
    </div>
    <% unless params[:controller] == "cocktails" && params[:action] == "home" %>
    <%= render "shared/footer" %>
    <% end %>


    <!-- Me lodea todas mis paginas de una: -->
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-suppress-warning' : true %>
    <!-- Me lodea cada pagina a la vez: -->
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for [cocktail, review] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit class: "btn btn-outline-success btn-block"%>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Maria Antonia Rojas @Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to cocktails_path, class: "navbar-brand" do %>
      <%= image_tag "final-logo.png" %>
  <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Add cocktail", new_cocktail_path, class: "btn btn-outline-success" %>
      </li>
      <li>
        <form action="/cocktails" method="get" class="form-inline">
          <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
          <!-- <input type="submit"> -->
        </form>
      </li>

      <!-- avatar dropdown -->
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/marojasl", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>